 export const datos = [
 
  {
    "Day": 26,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Agenda Sutentable en 5o Foro Puntos de Encuentro",
    "Text": "Prsentó 5 puntos para una política respecto al medio ambiente. 1) Evitar desperdicio de agua y alimentos. 2)Uso de energía limpia en hogares. 3) Políticas que preserven el capital biológico y ecológico, amigable con el turismo y recreación. 4) Ciudades inteligentes y sustentables. 5)Atraer 550 mil millones de pesos para inversiones en energías limpias.",
    "Media": "https://twitter.com/JoseAMeadeK/status/957069002194513920",
    "Media Credit": "Twitter",
    "Media Caption": "<a href=\"https://www.elsoldemexico.com.mx/mexico/politica/meade-presenta-cinco-propuestas-para-mejorar-el-medio-ambiente-750804.html\"> Leer nota </a>",
    "Media Thumbnail": "https://seeklogo.com/images/P/pri-logo-DFDD8E1515-seeklogo.com.png",
    "Type": "",
    "Group": "Propuestas",
    "Background": "",
    "Candidato": "Meade",
    "Tema": "Medio Ambiente",
    "Fuente": "https://www.elsoldemexico.com.mx/mexico/politica/meade-presenta-cinco-propuestas-para-mejorar-el-medio-ambiente-750804.html"
  },
  {
    "Day": 28,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Spots \"Conoce a José Antonio Meade",
    "Text": "Responde preguntas sobre su familia, estudios y experiencia en gobierno.",
    "Media": "https://www.youtube.com/watch?v=ovOv0enRrkc&list=PLsczVK0feV9HXkYsA3ROMiHPSyp32-Kfq&index=7",
    "Media Credit": "Youtube",
    "Media Caption": "<a href=\"https://www.youtube.com/playlist?list=PLsczVK0feV9HXkYsA3ROMiHPSyp32-Kfq\"> Ver todos los spots </a>",
    "Media Thumbnail": "https://i.imgur.com/jWQQQY1.png",
    "Type": "",
    "Group": "Campaña",
    "Background": "",
    "Candidato": "Meade",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 28,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Visita a Hidalgo",
    "Text": "Se reunió con Osorio Chong.",
    "Media": "https://cdn.heraldodemexico.com.mx/wp-content/uploads/2018/01/WhatsApp-Image-2018-01-28-at-18.04.22.jpeg",
    "Media Credit": "El Heraldo de México",
    "Media Caption": "<a href=\"https://heraldodemexico.com.mx/elecciones-2018/jose-antonio-meade-kuribrena/se-reunen-osorio-chong-y-meade-en-hidalgo/\"> Leer nota </a>",
    "Media Thumbnail": "https://i.imgur.com/JIQnSEx.png",
    "Type": "",
    "Group": "Entorno",
    "Background": "",
    "Candidato": "Meade",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 28,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Reunión con militantes de Nueva Alianza",
    "Text": "Se reunió en Hidalgo con 1500 aliancistas de la quinta circunscripción, junto con Omar Hayad gobernador del estado. Resaltó la importancia de las comunidades indígenas y resolver sus problemas de fondo. Luis Castro, líder de Nueva Alianza lo calificó como \"un tren de alta velocidad que convertirá México en una potencia",
    "Media": "http://www.eluniversal.com.mx/sites/default/files/styles/f03-651x400/public/2018/01/28/meade.jpeg?itok=ZE-U3lts",
    "Media Credit": "El Universal",
    "Media Caption": "<a href=\"http://www.eluniversal.com.mx/elecciones-2018/en-mexico-el-rostro-de-la-pobreza-es-el-de-una-mujer-indigena-dice-meade-en-hidalgo\"> Leer nota </a>",
    "Media Thumbnail": "https://i.imgur.com/jWQQQY1.png",
    "Type": "",
    "Group": "Campaña",
    "Background": "",
    "Candidato": "Meade",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 29,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Columna de Meade \"Hacia un crecimiento sostenido y sotenible",
    "Text": "Presenta su agenda sustentable como el camino para integrar los tres componentes del progreso, el económico, el social y el ambiental, en un concepto de desarrollo que no comprometa las futuras generaciones.",
    "Media": "https://twitter.com/JoseAMeadeK/status/957745052155023360",
    "Media Credit": "Twitter",
    "Media Caption": "<a href=\"http://www.milenio.com/firmas/jose_antonio_meade_kuribrena/crecimiento-pobreza-economia-desarrollo_sostenible-energia_limpia-ciudad_inteligente_18_1111868844.html\"> Leer nota </a>",
    "Media Thumbnail": "https://seeklogo.com/images/P/pri-logo-DFDD8E1515-seeklogo.com.png",
    "Type": "",
    "Group": "Propuestas",
    "Background": "",
    "Candidato": "Meade",
    "Tema": "Medio Ambiente",
    "Fuente": "http://www.milenio.com/firmas/jose_antonio_meade_kuribrena/crecimiento-pobreza-economia-desarrollo_sostenible-energia_limpia-ciudad_inteligente_18_1111868844.html"
  },
  {
    "Day": 29,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Políticas a favor de maestros",
    "Text": "En su visita a Hidalgo declaró que se requiere una política salarial agresiva para los maestros. Reconoció que la población mexicana tiene tres demandas: seguridad, empleos de calidad y viviendas dignas.",
    "Media": "https://twitter.com/JoseAMeadeK/status/957759491705004032",
    "Media Credit": "Twitter",
    "Media Caption": "<a href=\"http://www.excelsior.com.mx/nacional/2018/01/29/1216598\"> Leer nota </a>",
    "Media Thumbnail": "https://i.imgur.com/jWQQQY1.png",
    "Type": "",
    "Group": "Campaña",
    "Background": "",
    "Candidato": "Meade",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 29,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Resolvido",
    "Text": "Meade dijo \" hemos resolvido\" durante su reunión en Hidalgo al responder preguntas de militantes aliancistas. Su respuesta en Twitter fue hacer planas de \"Se dice resuelto…",
    "Media": "https://twitter.com/JoseAMeadeK/status/957806908148105216",
    "Media Credit": "Twitter",
    "Media Caption": "",
    "Media Thumbnail": "https://i.imgur.com/JIQnSEx.png",
    "Type": "",
    "Group": "Entorno",
    "Background": "",
    "Candidato": "Meade",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 29,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Columna de Meade \"Por un México seguro",
    "Text": "Presentó diez acciones para atacar la inseguridad. 1) Abatir la desigualdad y la pobreza. 2)Incrementar ingreso de los maestros. 3)Oficiales bien entrenados, protegidos y pagados. 4)Mejos tecnología (videovigilancia, denuncia exprés, mejor comunicación). 5) Bases de datos sobre los criminales. 6) Misma legislación a nivel nacional. 7) Mantener las Fuerzas Armadas en lugares conflictivos. 8) Quitar dinero, bienes y armas a criminales. 9)Castigar todo acto de corrupción. 10) Alto total a violencia de género.",
    "Media": "",
    "Media Credit": "",
    "Media Caption": "<a href=\"http://www.excelsior.com.mx/opinion/columnista-invitado-nacional/2018/01/29/1216679\"> Leer columna </a>",
    "Media Thumbnail": "https://seeklogo.com/images/P/pri-logo-DFDD8E1515-seeklogo.com.png",
    "Type": "",
    "Group": "Propuestas",
    "Background": "",
    "Candidato": "Meade",
    "Tema": "Seguridad",
    "Fuente": "http://www.excelsior.com.mx/opinion/columnista-invitado-nacional/2018/01/29/1216679"
  },
  {
    "Day": 29,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Visita Guerrero",
    "Text": "Diálogo con mujeres",
    "Media": "https://twitter.com/JoseAMeadeK/status/958063054838788096",
    "Media Credit": "Twitter",
    "Media Caption": "",
    "Media Thumbnail": "https://i.imgur.com/jWQQQY1.png",
    "Type": "",
    "Group": "Campaña",
    "Background": "",
    "Candidato": "Meade",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 29,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Propuestas a favor de las mujeres",
    "Text": "En Acapulco, presentó las siguientes acciones: 1) Créditos a la palabra 2)Otorgamiento de becas 3)Guarderías, preescolar y primaria con horario ampliado 4) Salario digno 5) Dignificar el trabajo doméstico",
    "Media": "http://wrmx00.epimg.net/radio/imagenes/2018/01/30/nacional/1517269555_757841_1517270578_noticia_normal.jpg",
    "Media Credit": "CuartoOscuro",
    "Media Caption": "<a href=\"http://wradio.com.mx/radio/2018/01/30/nacional/1517269555_757841.html\"> Leer nota </a>",
    "Media Thumbnail": "https://seeklogo.com/images/P/pri-logo-DFDD8E1515-seeklogo.com.png",
    "Type": "",
    "Group": "Propuestas",
    "Background": "",
    "Candidato": "Meade",
    "Tema": "Género",
    "Fuente": "http://wradio.com.mx/radio/2018/01/30/nacional/1517269555_757841.htm"
  },
  {
    "Day": 29,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Meade se reúne con militancia priísta en Guerrero",
    "Text": "Reconoció que la región tiene retos de seguridad muy grandes. Sin embargo, reconoció el trabajo de Héctor Astudillo en temas de seguridad.",
    "Media": "https://i2.sdpnoticias.com/sdpnoticias/2018/01/29/2144_jose-antonio-meade_620x350.jpg",
    "Media Credit": "SDP Noticias",
    "Media Caption": "<a href=\"http://www.elfinanciero.com.mx/nacional/en-guerrero-se-han-vivido-anos-muy-dificiles-dice-meade-a-militancia-priista.html\"> Leer nota </a>",
    "Media Thumbnail": "https://i.imgur.com/jWQQQY1.png",
    "Type": "",
    "Group": "Campaña",
    "Background": "",
    "Candidato": "Meade",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 31,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Feriberto Galindo se une a la campaña",
    "Text": "Suegro de Mikel Arriola se une como consejero polìtico",
    "Media": "https://luznoticiasrm.blob.core.windows.net/images/2018/01/31/heribertogalindoymeade2-focus-min0.02-0.21-1140-700.jpg",
    "Media Credit": "El Financiero",
    "Media Caption": "<a href=\"http://www.elfinanciero.com.mx/nacional/suegro-de-mikel-arriola-se-suma-a-la-campana-de-meade.html\"> Leer nota </a>",
    "Media Thumbnail": "https://i.imgur.com/6pKqN8a.png",
    "Type": "",
    "Group": "Actores",
    "Background": "",
    "Candidato": "Meade",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 30,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Meade y Mikel experimentan el tráfico",
    "Text": "Realizaron un recorrido de la Condesa a Santa Fe en hora pico y miden el tiempo. Ambos prometieron instrumentar diferentes medidas para acortar los tiempos de trabajo. El recorrido recibió críticas en redes sociales.",
    "Media": "https://twitter.com/JoseAMeadeK/status/958486250205229056",
    "Media Credit": "Twitter",
    "Media Caption": "<a href=\"https://www.eleconomista.com.mx/politica/Meade-y-Mikel-Arriola-experimentan-el-trafico-20180130-0157.html\"> Leer nota </a>",
    "Media Thumbnail": "https://i.imgur.com/jWQQQY1.png",
    "Type": "",
    "Group": "Campaña",
    "Background": "",
    "Candidato": "Meade",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 30,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Columna de Meade \"Es la hora de las mujeres y las niñas",
    "Text": "Presenta 5 acciones a favor de las mujeres. Mismas que propuso en acaulpo, Guerrero. Habla sobre garantizar a las mujeres el ejercicio pleno de sus derechos y libertades, debido a que es una condición indispensable para el crecimiento y desarrollo cultural del país.",
    "Media": "https://twitter.com/JoseAMeadeK/status/958177615268818950",
    "Media Credit": "Twiiter",
    "Media Caption": "<a href=\"https://www.elsoldemexico.com.mx/analisis/es-la-hora-de-las-mujeres-y-las-ninas-756160.html\"> Leer nota </a>",
    "Media Thumbnail": "https://i.imgur.com/jWQQQY1.png",
    "Type": "",
    "Group": "Campaña",
    "Background": "",
    "Candidato": "Meade",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 31,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Meade visita obras de AICM",
    "Text": "Meade defiende obras del aeropuerto, califico de ocurrencia la amenaza de AMLO de cancelar la obra. Advirtió que cancelalrlo sería incosntitucional y que se perdería la oportunidad de generar casi medio millón de empleos.",
    "Media": "https://twitter.com/JoseAMeadeK/status/958887525350690816",
    "Media Credit": "Twitter",
    "Media Caption": "<a href=\"https://www.eleconomista.com.mx/politica/Meade-defiende-obras-del-nuevo-aeropuerto-20180131-0155.html\">Leer nota </a>",
    "Media Thumbnail": "https://i.imgur.com/jWQQQY1.png",
    "Type": "",
    "Group": "Campaña",
    "Background": "",
    "Candidato": "Meade",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 12,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Registro como Precandidato",
    "Text": "Se registró como Precandidato a Presidente y tocó los ejes de su plan de gobierno",
    "Media": "https://www.youtube.com/watch?v=Ce3RfrKn6Tk&feature=youtu.be",
    "Media Credit": "Youtube",
    "Media Caption": "<a href=\"https://www.youtube.com/watch?v=Ce3RfrKn6Tk&feature=youtu.be\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/S9RVwJo.png",
    "Type": "",
    "Group": "Campaña",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 13,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Firma alianza \"Juntos haremos historia",
    "Text": "Firmó la alianza y explicó porque van en conjunto y las características que los unen. Firman Andrés Manuel López Obrador, Alberto Anaya, presidente del PT y Eric Flores, presidente del PES",
    "Media": "http://lopezobrador.org.mx/wp-content/uploads/2017/12/13-dic-2017-Firma-Alianza-06-1024x722.jpg",
    "Media Credit": "www.lopezobrador.org.mx",
    "Media Caption": "<a href=\"http://lopezobrador.org.mx/2017/12/13/firma-de-alianza-juntos-haremos-historiaentre-morena-pes-y-pt/\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/S9RVwJo.png",
    "Type": "",
    "Group": "Campaña",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 13,
    "Time": "10:26",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Debate sobre discurso de AMLO",
    "Text": "Wradio invitó a dos personajes a su programa a hablar sobre el primer discurso de Pre campaña de Amlo. Uno en Favor y uno en contra",
    "Media": "https://twitter.com/WRADIOMexico/status/940961626425044992",
    "Media Credit": "W radio",
    "Media Caption": "<a href=\"http://wradio.com.mx/programa/2017/12/13/asi_las_cosas/1513181922_230930.html\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/TNn8sGO.png",
    "Type": "",
    "Group": "Entorno",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 13,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "INE y televisoras deben garantizar elecciones limpias",
    "Text": "Amlo habla sobre las campañas mediàticas en su contra.",
    "Media": "http://www.animalpolitico.com/wp-content/uploads/2017/12/amlo-lopez-obrador-inseguridad-960x500.jpg",
    "Media Credit": "AMLO pagina oficial",
    "Media Caption": "<a href=\"http://lopezobrador.org.mx/secciones/comunicados/page/2/\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/TNn8sGO.png",
    "Type": "",
    "Group": "Entorno",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 14,
    "Time": "11:26",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Entrevista a Mancera",
    "Text": "Mancera criticó la propuesta de AMLO de darle apoyo económico a jovenes que no estudian ni laboral",
    "Media": "https://www.eleconomista.com.mx/__export/1512421104237/sites/eleconomista/img/2017/09/17/informe-mancerita-notimex.jpg_73367373.jpg",
    "Media Credit": "Notimex",
    "Media Caption": "<a href=\"https://www.eleconomista.com.mx/politica/Inviable-propuesta-de-AMLO-de-dar-recursos-a-ninis-Mancera-20171213-0063.html\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/t46Q6PE.png",
    "Type": "",
    "Group": "Actores",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 14,
    "Time": "12:43",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "AMLO presenta gabinete",
    "Text": "Presentó a los que serán sus secretarios",
    "Media": "http://lopezobrador.org.mx/wp-content/uploads/2017/12/Gabinete08-770x539.jpg",
    "Media Credit": "AMLO pagina oficial",
    "Media Caption": "<a href=\"http://lopezobrador.org.mx/2017/12/14/presenta-amlo-gabinete-presidencial-2018-2024-video/\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/S9RVwJo.png",
    "Type": "",
    "Group": "Campaña",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 14,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "La alianza conservadora de AMLO con el PES",
    "Text": "Alianza no sólo busca sumar los votos y ganar, sino que AMLO en realidad tiene parte de ideología conservadora",
    "Media": "http://www.excelsior.com.mx/media/opinion/2017/03/02/1631690.jpg",
    "Media Credit": "Excelsior",
    "Media Caption": "<a href=\"http://www.excelsior.com.mx/opinion/leo-zuckermann/2017/12/14/1207754\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/TNn8sGO.png",
    "Type": "",
    "Group": "Entorno",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 14,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Ideologías puestas entre PES y MORENA. Sólo van por votos",
    "Text": "Yuriria Sierra tiene los mismos puntos que Zuckermann",
    "Media": "http://www.excelsior.com.mx/media/opinion/2015/04/28/1204728.jpg",
    "Media Credit": "Excelsior",
    "Media Caption": "<a href=\"http://www.excelsior.com.mx/opinion/yuriria-sierra/2017/12/14/1207764\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/TNn8sGO.png",
    "Type": "",
    "Group": "Entorno",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 14,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Los peligrosos pasos de AMLO",
    "Text": "Pablo Hiriart dice que las propuestas de AMLO sobre la guardia nacional, la aministía a narcos y los subsidios a los jóvenes no cumplen con las vialidades del Estado de Derecho Mexicano. En caso, muy probable, de que no tenga los recursos para cumplir con sus propuestas de campaña, alegará que lo estan frenando los mismos actores de siempre",
    "Media": "http://www.elfinanciero.com.mx/files/article_main/uploads/2017/12/14/5a329b21330f8.png",
    "Media Credit": "El Financiero",
    "Media Caption": "<a href=\"http://www.elfinanciero.com.mx/opinion/los-peligrosos-pasos-de-amlo.html\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/TNn8sGO.png",
    "Type": "",
    "Group": "Entorno",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 15,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Primer acto de campaña en CDMX",
    "Text": "",
    "Media": "https://www.youtube.com/watch?v=5LGfkUH0jY0#action=share",
    "Media Credit": "Twitter",
    "Media Caption": "<a href=\"https://www.youtube.com/watch?v=5LGfkUH0jY0#action=share\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/S9RVwJo.png",
    "Type": "",
    "Group": "Campaña",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 15,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Esto soy yo",
    "Text": "presentación del documental autobiográfico ‘Esto Soy’, producido por Epigmenio Ibarra y Verónica Velasco.",
    "Media": "https://www.youtube.com/watch?v=TClF8dK7EE0#action=share",
    "Media Credit": "Pagina oficial de AMLO",
    "Media Caption": "<a href=\"https://www.youtube.com/watch?v=TClF8dK7EE0#action=share\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/S9RVwJo.png",
    "Type": "",
    "Group": "Campaña",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 15,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Gabinete de AMLO habla",
    "Text": "",
    "Media": "http://www.animalpolitico.com/wp-content/uploads/2017/12/IMG_20171214_123333-e1513366249157-960x500.jpg",
    "Media Credit": "Cuarto oscuro",
    "Media Caption": "<a href=\"http://www.animalpolitico.com/2017/12/gabinete-lopez-obrador-propuestas/\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/t46Q6PE.png",
    "Type": "",
    "Group": "Actores",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 15,
    "Time": "06:44",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Personajes con pasado priista se cuelan a gabinete de AMLO",
    "Text": "",
    "Media": "https://www.debate.com.mx/__export/1513345357003/sites/debate/img/2017/12/15/gabinete.jpg_539665225.jpg",
    "Media Credit": "Debate - Sinaloa",
    "Media Caption": "<a href=\"https://www.debate.com.mx/politica/Personajes-con-pasado-priista-se-cuelan-a-gabinete-de-AMLO-20171215-0019.html\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/TNn8sGO.png",
    "Type": "",
    "Group": "Entorno",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 15,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "AMLO pide tranquilidad ante aprobación de Ley de Seguridad Interior porque no se va a reprimir al pueblo",
    "Text": "",
    "Media": "https://i0.wp.com/ljz.mx/wp-content/uploads/2017/12/la-jornada-zacatecas-amlo3_lj.jpg?fit=1024%2C683",
    "Media Credit": "La jornada Zacatecas",
    "Media Caption": "<a href=\"http://ljz.mx/2017/12/15/pide-amlo-tranquilidad-ante-aprobacion-de-ley-de-seguridad-interior/\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/TNn8sGO.png",
    "Type": "",
    "Group": "Entorno",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 15,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Enfrentamiento entre simpatizantes de AMLO y personal de la delegación Coyoacán",
    "Text": "",
    "Media": "http://az778189.vo.msecnd.net/media/fotos/g/7f131d7fc35a810070fec16bd9fff9ac.png",
    "Media Credit": "twitter",
    "Media Caption": "<a href=\"http://www.mvsnoticias.com/#!/noticias/enfrentamiento-entre-simpatizantes-de-amlo-y-personal-de-la-delegacion-coyoacan-606\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/TNn8sGO.png",
    "Type": "",
    "Group": "Entorno",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 16,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "AMLO encabeza encuestas",
    "Text": "En la zona rural y urbana de Sinaloa, AMLO es el más conocido. Margarita va en segundo lugar",
    "Media": "https://www.debate.com.mx/export/sites/debate/img/2017/12/16/7.jpg_193478738.jpg",
    "Media Credit": "El Debate Sinaloa",
    "Media Caption": "<a href=\"https://www.debate.com.mx/politica/AMLO-y-Morena-arrancan-con-ventaja-en-Sinaloa--20171216-0158.html\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/TNn8sGO.png",
    "Type": "",
    "Group": "Entorno",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 16,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Los Secretarios más jóvenes en el gabinete de AMLO",
    "Text": "Dentro del gabinete de AMLO hay dos jóvenes de 30 y 35 años.",
    "Media": "http://www.nacion321.com/files/article_main/uploads/2017/12/14/c88d8d0a60977_position1_retina.jpg",
    "Media Credit": "Nación 321",
    "Media Caption": "<a href=\"http://www.nacion321.com/elecciones/conoce-a-los-2-millennials-que-estan-en-el-gabinete-de-amlo\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/TNn8sGO.png",
    "Type": "",
    "Group": "Entorno",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 16,
    "Time": "18:39",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Llamado a defender",
    "Text": "",
    "Media": "https://youtu.be/Zq7PBhBijrc",
    "Media Credit": "Twitter",
    "Media Caption": "<a href=\"https://youtu.be/Zq7PBhBijrc\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/S9RVwJo.png",
    "Type": "",
    "Group": "Campaña",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 17,
    "Time": "15:59",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "AMLO propone subirle el sueldo a policías, marinos y militares para reducir la inseguridad",
    "Text": "acciones básicas contra la inseguridad",
    "Media": "http://www.animalpolitico.com/wp-content/uploads/2017/12/amlo-lopez-obrador-inseguridad-960x500.jpg",
    "Media Credit": "www.lopezobrador.org.mx",
    "Media Caption": "<a href=\"http://www.animalpolitico.com/2017/12/amlo-inseguridad-plan-decalogo/\">Leer nota</a>",
    "Media Thumbnail": "https://seeklogo.com/images/M/movimiento-de-regeneracion-nacional-morena-logo-7660423A28-seeklogo.com.png",
    "Type": "",
    "Group": "Propuestas",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "Seguridad",
    "Fuente": "http://www.animalpolitico.com/2017/12/amlo-inseguridad-plan-decalogo/"
  },
  {
    "Day": 18,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Mover secretarías",
    "Text": "a propuesta contempla, por ejemplo, trasladar a la Secretaría de Turismo a Chetumal, Quintana Roo; Semarnat a Mérida, Yucatán; Pemex a Ciudad del Carmen, Campeche; SENER a Villahermosa, Tabasco; CFE a Tuxtla Gutiérrez, Chiapas; Conagua a Veracruz; Sedesol a Oaxaca, y SEP a Puebla.",
    "Media": "https://cdn.forbes.com.mx/2016/09/amlo-3-640x400.jpg",
    "Media Credit": "Morena",
    "Media Caption": "<a href=\"https://www.forbes.com.mx/30-anos-mover-secretarias-estados-propuesta-amlo/\">Leer nota</a>",
    "Media Thumbnail": "https://seeklogo.com/images/M/movimiento-de-regeneracion-nacional-morena-logo-7660423A28-seeklogo.com.png",
    "Type": "",
    "Group": "Propuestas",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "Administración Pública",
    "Fuente": "https://www.forbes.com.mx/30-anos-mover-secretarias-estados-propuesta-amlo/"
  },
  {
    "Day": 18,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Revisión de fondos para reconstrucción de la ciudad",
    "Text": "AMLO propone dar 3600 pesos a jóvenes para que lo destinen a aprender oficios y se integren a la vida laboral.,",
    "Media": "https://abrilveja.files.wordpress.com/2016/05/duvida_carreira-original1.jpeg?quality=70&strip=info&w=1024",
    "Media Credit": "Veja",
    "Media Caption": "<a href=\"http://www.mvsnoticias.com/#!/noticias/propone-amlo-dar-beca-de-2-mil-400-pesos-mensuales-a-ninis-video-410\">Leer nota</a>",
    "Media Thumbnail": "https://seeklogo.com/images/M/movimiento-de-regeneracion-nacional-morena-logo-7660423A28-seeklogo.com.png",
    "Type": "",
    "Group": "Propuestas",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "Desarrollo Social",
    "Fuente": "http://www.mvsnoticias.com/#!/noticias/propone-amlo-dar-beca-de-2-mil-400-pesos-mensuales-a-ninis-video-410"
  },
  {
    "Day": 18,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "AMLO se registra como candidato al PES",
    "Text": "Andrés Manuel negó que las diferencias entre MORENA y PES fueran abismales",
    "Media": "http://tiempodigital.mx/wp-content/uploads/2017/12/05.AMLO_PES.jpg",
    "Media Credit": "Notimex",
    "Media Caption": "<a href=\"http://www.excelsior.com.mx/nacional/2017/12/18/1208594\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/S9RVwJo.png",
    "Type": "",
    "Group": "Campaña",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 18,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "¿quién ofrece más a los jóvenes?",
    "Text": "35 millones de Millenials que comprenden la edad de entre 18 a 34 años, y representan poco más del 40% de la lista nominal de electores, según el último corte del 8 de diciembre de 2017.",
    "Media": "http://www.nacion321.com/files/article_main/uploads/2017/12/14/a9b7ba70783b6_position1_retina.jpg",
    "Media Credit": "Cuarto oscuro",
    "Media Caption": "<a href=\"http://www.nacion321.com/elecciones/amlo-meade-o-anaya-quien-ofrece-mas-a-los-jovenes\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/TNn8sGO.png",
    "Type": "",
    "Group": "Entorno",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 18,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Anuncia nombramiento de Secretario de SSP",
    "Text": "",
    "Media": "http://lopezobrador.org.mx/wp-content/uploads/2017/12/Calpulalpan-03-1024x683.jpg",
    "Media Credit": "AMLO pagina oficial Boletín 00-007",
    "Media Caption": "<a href=\"http://lopezobrador.org.mx/secciones/comunicados/page/3/\">Leer nota</a>",
    "Media Thumbnail": "https://seeklogo.com/images/M/movimiento-de-regeneracion-nacional-morena-logo-7660423A28-seeklogo.com.png",
    "Type": "",
    "Group": "Propuestas",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "Administración Pública",
    "Fuente": "http://lopezobrador.org.mx/secciones/comunicados/page/3/"
  },
  {
    "Day": 19,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "AMLO toma coctel de pastillas",
    "Text": "Ante la propuesta de Meade de hacer exámenes físicos a las candidatos, Andrés Manuel respondió que hay problemas más importantes que atender",
    "Media": "http://lopezobrador.org.mx/wp-content/uploads/2017/12/Huautla-de-Jim%C3%A9nez-04-e1513727984880-683x1024.jpg",
    "Media Credit": "El Financiero",
    "Media Caption": "<a href=\"http://www.elfinanciero.com.mx/nacional/tomo-un-coctel-de-pastillas-a-diario-lopez-obrador.html\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/TNn8sGO.png",
    "Type": "",
    "Group": "Entorno",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 19,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "El voto es de quien lo trabaja",
    "Text": "Confronta decisiones de Meade sobre gasolinazo",
    "Media": "https://pbs.twimg.com/media/DRiWsIAV4AAb85K.jpg",
    "Media Credit": "Twitter",
    "Media Caption": "<a href=\"https://twitter.com/lopezobrador_/status/943669817944526848\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/S9RVwJo.png",
    "Type": "",
    "Group": "Campaña",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 20,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Condena asesinatos a periodistas",
    "Text": "AMLO tocó el tema de ataque a los peridistas, la mala administración de Yunes y la posición de los Candidatos Independientes en las encuestas.",
    "Media": "http://lopezobrador.org.mx/wp-content/uploads/2017/12/Tlalchinol-1024x683.jpg",
    "Media Credit": "AMLO pagina oficial Boletín 00-009",
    "Media Caption": "<a href=\"http://lopezobrador.org.mx/secciones/comunicados/page/3/\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/S9RVwJo.png",
    "Type": "",
    "Group": "Campaña",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 21,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Spot pidiendo ayuda sobre levantamiento de censo sobre viviendas destruídad en los temblores pasados.",
    "Text": "Programa de rehabilitación de la vivienda",
    "Media": "https://youtu.be/SISw48YI0Vg",
    "Media Credit": "Youtube",
    "Media Caption": "<a href=\"https://youtu.be/SISw48YI0Vg\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/S9RVwJo.png",
    "Type": "",
    "Group": "Campaña",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 21,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Plan de emergencia ante la reforma fiscal de EU",
    "Text": "Anuncio que después de la descentralización la Secretaría de la Urbano estaría en Hidalgo",
    "Media": "http://lopezobrador.org.mx/wp-content/uploads/2017/12/Cuautpec-1024x683.jpg",
    "Media Credit": "AMLO pagina oficial Boletín 00-011",
    "Media Caption": "<a href=\"http://lopezobrador.org.mx/secciones/comunicados/page/3/\">Leer nota</a>",
    "Media Thumbnail": "https://seeklogo.com/images/M/movimiento-de-regeneracion-nacional-morena-logo-7660423A28-seeklogo.com.png",
    "Type": "",
    "Group": "Propuestas",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "Administración Pública",
    "Fuente": "http://lopezobrador.org.mx/secciones/comunicados/page/3/"
  },
  {
    "Day": 22,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "Informe de los apoyos entregados a los damnificados de los sismos",
    "Text": "Reporta finanzas del \"Donativo obtenidos en el fideicomiso por los demás al 21 de diciembre\". Han entregado 14396 apoyos que equivalen a $34,550,400.",
    "Media": "https://www.youtube.com/watch?v=UR2uuyCCaNw&feature=youtu.be",
    "Media Credit": "Youtube",
    "Media Caption": "<a href=\"https://www.youtube.com/watch?v=UR2uuyCCaNw&feature=youtu.be\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/S9RVwJo.png",
    "Type": "",
    "Group": "Campaña",
    "Background": "",
    "Candidato": "AMLO",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 24,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "PUEBLA. Martha Alonso, esposa de Moreno Valle, se registra su precandidatura",
    "Text": "Martha Érika Alonso, esposa del ex mandatario poblano Rafael Moreno Valle, se registró como precandidata del PAN a la gubernatura.",
    "Media": "http://www.eluniversal.com.mx/sites/default/files/styles/f03-651x400/public/2018/01/24/martha_erika.jpg?itok=Qs3ByJ7I",
    "Media Credit": "El Universal",
    "Media Caption": "",
    "Media Thumbnail": "https://seeklogo.com/images/P/PAN-logo-5C037F689C-seeklogo.com.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "PAN",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 28,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "PUEBLA. Enrique Doger, precandidato de unidad para el gobierno de Puebla",
    "Text": "En reunión celebrada en las oficinas del CEN del PRI, se llegó al consenso de que la mejor opción para contender y ganar el gobierno del estado de Puebla es Enrique Doger Guerrero.",
    "Media": "http://pri.org.mx/BancoInformacion/files/Imagenes/27006-1-15_40_19.jpg",
    "Media Credit": "PRI",
    "Media Caption": "",
    "Media Thumbnail": "https://seeklogo.com/images/P/pri-logo-DFDD8E1515-seeklogo.com.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "PRI",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 31,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "PUEBLA. Miguel Barbosa se registra como precandidato de MORENA",
    "Text": "Luis Miguel Barbosa Huerta se registró como precandidato de MORENA a la gubernatura de Puebla, después de pedir licencia como Senador de la República.",
    "Media": "https://cdn.oem.com.mx/elsoldepuebla/2018/01/barbosa-600x400.jpg",
    "Media Credit": "El Sol de Puebla",
    "Media Caption": "",
    "Media Thumbnail": "https://seeklogo.com/images/M/movimiento-de-regeneracion-nacional-morena-logo-7660423A28-seeklogo.com.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "MORENA",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 24,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "PUEBLA. MORENA registra coalición electoral en Puebla",
    "Text": "Los partidos MORENA, PT y PES solicitaron su registro ante el Instituto Electoral de Puebla como coalición para enfrentar la elección a la gubernatura, diputaciones locales y alcaldías. MORENA se quedará con el 50% de nominaciones; el resto se dividirá por iguales entre el PT y PES.",
    "Media": "http://www.eluniversal.com.mx/sites/default/files/styles/f03-651x400/public/2018/01/24/coalicion_puebla.jpg?itok=BaHoDpIe",
    "Media Credit": "El Universal",
    "Media Caption": "",
    "Media Thumbnail": "https://seeklogo.com/images/M/movimiento-de-regeneracion-nacional-morena-logo-7660423A28-seeklogo.com.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "MORENA",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 22,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "PUEBLA. Conforman coalición \"Por Puebla al Frente",
    "Text": "La coalición que integran el PAN, PRD y MC fue nombrada \"Por Puebla al Frente\" y abarca la gubernatura y 22 distritos locales. De estos, 10 corresponderán al PAN, 5 al PRD 3 a MC y los otros cuatro a dos partidos locales, Compromiso por Puebla y Pacto Social de Integración.",
    "Media": "http://www.diariocambio.com.mx/2018/zoon-politikon/item/313-conforman-megacoalicion-por-puebla-al-frente-iran-juntos-en-22-distritos-locales",
    "Media Credit": "Diario Cambio",
    "Media Caption": "",
    "Media Thumbnail": "https://seeklogo.com/images/P/PAN-logo-5C037F689C-seeklogo.com.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "PAN",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 30,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "PUEBLA. Encuesta Mendoza Blanco & Asociados",
    "Text": "El sondeo realizado por Mendoza Blanco & Asociados muestra las siguientes preferencias efectivas: Martha Alonso 45%, Enrique Doger 20%, Miguel Barbosa 28%, Juan Natale 5% y Cirilo Salas 2%. Tasa de no respuesta: 19%. Encuesta realizada del 19 al 20 de enero en vivienda a 1,200 personas.",
    "Media": "http://www.regionalpuebla.mx/media/k2/items/cache/a140e125ba584a200100a6bfe05e0521_XL.jpg",
    "Media Credit": "Regional Puebla",
    "Media Caption": "",
    "Media Thumbnail": "https://i.imgur.com/Me2bJCH.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "Encuesta",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 11,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "TABASCO. Pide Adán López registro como precandidato a MORENA",
    "Text": "Adán Augusto López Hernández, exdirigente estatal de Morena en Tabasco, solicitó ante la Comisión Nacional de Elecciones, su registro como precandidato al Gobierno de Tabasco para el proceso electoral del 2018.",
    "Media": "https://cdn.oem.com.mx/elheraldodetabasco/2017/12/loc10pide.jpg",
    "Media Credit": "El Heraldo de Tabasco",
    "Media Caption": "",
    "Media Thumbnail": "https://seeklogo.com/images/M/movimiento-de-regeneracion-nacional-morena-logo-7660423A28-seeklogo.com.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "MORENA",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 22,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "TABASCO. PRD cierra filas con Gerardo Gaudiano para ganar gubernatura de Tabasco",
    "Text": "El Presidente Nacional del PRD, Manuel Granados, dio a conocer que los resultados de la encuesta que realizó este instituto político para elegir al candidato a la gubernatura del estado de Tabasco arrojó como mejor posicionado a Gerardo Gaudiano Rovirosa, quien será el candidato del PRD al gobierno de Tabasco.",
    "Media": "http://www.prd.org.mx/images/fotos/flashmo_940x400_02.jpg",
    "Media Credit": "PRD",
    "Media Caption": "",
    "Media Thumbnail": "http://www.prdtabasco.org.mx/images/logo_prd3.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "PRD",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 26,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "TABASCO. La Dip. Federal Georgina Trujillo se registró como precandidata única del PRI para gobernar Tabasco",
    "Text": "La diputada federal del PRI, Georgina Trujillo Zentella, se registró como precandidata única de ese partido al gobierno del estado.",
    "Media": "https://cdn.proceso.com.mx/media/2017/12/Georgina-Trujillo-1078x800.jpg",
    "Media Credit": "Proceso",
    "Media Caption": "",
    "Media Thumbnail": "https://seeklogo.com/images/P/pri-logo-DFDD8E1515-seeklogo.com.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "PRI",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 3,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "TABASCO. Instituto Electoral tabasqueño aprobó coalición \"Juntos Haremos Historia",
    "Text": "El Consejo Estatal del Instituto Electoral y de Participación Ciudadana de Tabasco aprobó el registro de la coalición \"Juntos haremos historia\", integrada por los partidos MORENA-PT-PES. La coalición será únicamente para la gubernatura, por lo que los tres partidos podrían ir en candidaturas comunes para las 17 presidencias municipales y 35 diputados locales o contender solos.",
    "Media": "https://cdn.proceso.com.mx/media/2017/09/sesion-del-IEPCT-702x468.jpg",
    "Media Credit": "Proceso",
    "Media Caption": "",
    "Media Thumbnail": "https://seeklogo.com/images/M/movimiento-de-regeneracion-nacional-morena-logo-7660423A28-seeklogo.com.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "MORENA",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 3,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "TABASCO. Instituto Electoral tabasqueño aprobó coalición \"Por Tabasco al Frente",
    "Text": "El Consejo Estatal del Instituto Electoral y de Participación Ciudadana de Tabasco aprobó el registro de la coalición \"Por Tabasco al frente\", integrada por los partidos PAN-PRD-MC. La alianza será tanto para la gubernatura, como para las 17 alcaldías y 35 diputaciones locales.",
    "Media": "https://cdn.proceso.com.mx/media/2017/09/sesion-del-IEPCT-702x468.jpg",
    "Media Credit": "Proceso",
    "Media Caption": "",
    "Media Thumbnail": "http://www.prdtabasco.org.mx/images/logo_prd3.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "PRD",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 24,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "TABASCO. No habrá coalición PRI-PANAL-PVEM en Tabasco",
    "Text": "El PRI no irá en coalición en la elección local, afirmó el dirigente estatal Gustavo de la Torre Zurita, quien señaló que podrían buscar ir en una candidatura común para gobernador con el PVEM y PANAL, pero será una decisión que se tome más adelante. Por lo pronto, hoy que se termina el plazo oficial, está descartado que vayan juntos estos tres partidos políticos.",
    "Media": "http://www.tabascohoy.com/nota/423222/no-habra-coalicion-pri-panal-pvem-en-tabasco",
    "Media Credit": "Tabasco Hoy",
    "Media Caption": "",
    "Media Thumbnail": "https://seeklogo.com/images/P/pri-logo-DFDD8E1515-seeklogo.com.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "PRI",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 18,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "TABASCO. Encuesta Berumen",
    "Text": "El sondeo realizado por Berumen muestra las siguientes preferencias: Adán López 30.7%, Gerardo Gaudiano 13.8%, Georgina Trujillo 8.4%, Jesús Alí de la Torre (Independiente) 2.7% y Óscar Cantón (independiente) 1.5%.",
    "Media": "https://i1.wp.com/s3-us-west-1.amazonaws.com/diariobasta/wp-content/uploads/2017/12/18034500/Captura11.jpg?resize=600%2C265",
    "Media Credit": "Diario Basta",
    "Media Caption": "",
    "Media Thumbnail": "https://i.imgur.com/Me2bJCH.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "Encuesta",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 7,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "VERACRUZ. Validan registro de Pepe Yunes, precandidato del PRI",
    "Text": "La Comisión Estatal de Procesos Internos del PRI dictaminó ayer como procedente la solicitud de registro de la precandidatura de “unidad” de José Francisco Yunes Zorrilla a la gubernatura de Veracruz.",
    "Media": "https://www.elmundodecordoba.com/images/n2pfile/20180107/admin-fotos-2018-01-05-General-447985.jpg.jpg",
    "Media Credit": "El Mundo de Córdoba",
    "Media Caption": "José Yunes Zorrilla",
    "Media Thumbnail": "https://seeklogo.com/images/P/pri-logo-DFDD8E1515-seeklogo.com.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "PRI",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 23,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "VERACRUZ. Miguel Ángel Yunes se registra como precandidato del PAN",
    "Text": "El alcalde de Boca del Río, Miguel Ángel Yunes Márquez, hijo del gobernador actual Yunes Linares, se registró este sábado como precandidato del PAN a la gubernatura de Veracruz para el periodo 2018-2024.",
    "Media": "https://cdn.proceso.com.mx/media/2013/07/eg5.jpg",
    "Media Credit": "Proceso",
    "Media Caption": "Miguel Ángel Yunes Márquez",
    "Media Thumbnail": "https://seeklogo.com/images/P/PAN-logo-5C037F689C-seeklogo.com.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "PAN",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 3,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "VERACRUZ. MORENA, PT Y PES registran coalición en Veracruz",
    "Text": "MORENA, PT y PES solicitaron el registro de la coalición \"Juntos Haremos Historia\" que competirá por la Gubernatura de Veracruz.",
    "Media": "https://www.elmundodecordoba.com/images/n2pfile/20180103/721793120180103.jpg",
    "Media Credit": "El Mundo de Córdoba",
    "Media Caption": "",
    "Media Thumbnail": "https://seeklogo.com/images/M/movimiento-de-regeneracion-nacional-morena-logo-7660423A28-seeklogo.com.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "MORENA",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 2,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "VERACRUZ. Cuitláhuac García buscará la gubernatura de Veracruz por segunda ocasión",
    "Text": "Por segunda ocasión consecutiva, Cuitláhuac García Jiménez buscará la gubernatura de Veracruz avalado por MORENA y en su registro como precandidato, vaticinó que esta vez las condiciones son distintas, pues presumió que en estas elecciones de julio próximo Andrés Manuel López Obrador también “viene en la boleta”.",
    "Media": "https://cdn.proceso.com.mx/media/2018/01/Cuitl%C3%A1huac-Garc%C3%ADa-1078x800.jpg",
    "Media Credit": "Proceso",
    "Media Caption": "Cuitláhuac García al registrarse como precandidato.",
    "Media Thumbnail": "https://seeklogo.com/images/M/movimiento-de-regeneracion-nacional-morena-logo-7660423A28-seeklogo.com.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "MORENA",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 3,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "VERACRUZ. PRI y Verde van en alianza en elecciones en Veracruz",
    "Text": "La coalición \"Por Un Veracruz Mejor\" integrada por el PRI y el PVEM presentó su solicitud de registro para las elecciones locales, en las cuales se renoevará la gubernatura y 30 diputaciones locales. De los treinta distritos, veinte serán abanderados del PRI y diez del PVEM.",
    "Media": "http://www.eluniversal.com.mx/sites/default/files/styles/f03-651x400/public/2018/01/03/010alianza_veracruz.jpg?itok=xDdSU2it",
    "Media Credit": "El Universal",
    "Media Caption": "",
    "Media Thumbnail": "https://seeklogo.com/images/P/pri-logo-DFDD8E1515-seeklogo.com.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "PRI",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 3,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "VERACRUZ. Registran coalición entre PAN, PRD y MC en Veracruz.",
    "Text": "Fue entregada la solicitud formal para el registro de la coalición “Por Veracruz al frente”, integrada por el PAN, PRD y MC con la finalidad de postular al candidato a gobernador y la totalidad de las fórmulas de candidatos a diputados locales.",
    "Media": "http://libertadbajopalabra.com/wp-content/uploads/2018/01/cppm2-600x600.jpg",
    "Media Credit": "Libertad Bajo Palabra",
    "Media Caption": "Solicitud formal para el registro de la coalición \"Por Veracruz al Frente",
    "Media Thumbnail": "https://seeklogo.com/images/P/PAN-logo-5C037F689C-seeklogo.com.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "PAN",
    "Tema": "",
    "Fuente": ""
  },
 {
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "JALISCO. Si hoy hubiera elecciones para Gobernador de Jalico ¿por quién votaría?",
    "Text": "",
    "Media": "http://o.aolcdn.com/hss/storage/midas/30eb35409bcf1a2882a0b1609b3cca05/206053165/ENCUESTA+JALISCO.jpg",
    "Media Credit": "Reforma",
    "Media Caption": "<a href=\"http://www.huffingtonpost.com.mx/2018/01/24/el-pri-no-figura-como-favorito-en-ninguna-de-las-9-gubernaturas-que-se-disputaran-en-2018_a_23340370/\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/Me2bJCH.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "ENCUESTAS",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": "",
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "JALISCO. Encuesta Massive Caller",
    "Text": "Encuesta telefónica a hombres y mujeres mayores de 18 que tengan teléfono. Muestreo representativo tipo cuantitativo. Marco muestral: números telefónicos de los estados. Llamadas aleatorias por una grabación. Última fecha de levantamiento: 16 de enero. 1000 encuestas levantadas.",
    "Media": "https://i2.sdpnoticias.com/sdpnoticias/2018/01/17/20180117171456_de8acdf5_0ebf_49a8_ad41_a933c35e4685_620x6200.jpeg",
    "Media Credit": "SDP Noticias",
    "Media Caption": "<a href=\"https://www.sdpnoticias.com/nacional/2018/01/17/encuestas-estatales-morena-gana-mas-que-el-pan-y-el-pri-no-gana-nada\">Leer nota</a>",
    "Media Thumbnail": "https://i.imgur.com/Me2bJCH.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "ENCUESTAS",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 31,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "JALISCO. Buscará Miguel Ángel Martínez candidatura a la gubernatura por el PAN",
    "Text": "Desde enero de 2016 fungiera como presidente del PAN en Jalisco, anunció que deja temporalmente el cargo con miras a buscar la candidatura del partido a la gubernatura del estado.",
    "Media": "http://www.ntrguadalajara.com/evidimg/2018-01-31_05-01-01___6413.jpg",
    "Media Credit": "El Diario",
    "Media Caption": "<a href=\"http://www.ntrguadalajara.com/post.php?id_nota=91627\">Leer nota</a>",
    "Media Thumbnail": "https://seeklogo.com/images/P/PAN-logo-5C037F689C-seeklogo.com.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "PAN",
    "Tema": "",
    "Fuente": ""
  },
  {
    "Day": 4,
    "Time": "",
    "End Year": "",
    "End Month": "",
    "End Day": "",
    "End Time": "",
    "Display Date": "",
    "Headline": "JALISCO. Martínez Espinosa sería “juez y parte” si es candidato",
    "Text": "Aunque hay otros que buscan conseguir la candidatura del Partido Acción Nacional (PAN) a la gubernatura de Jalisco, César Madrigal Díaz afirmó que es el único militante registrado para competir por el cargo. Consideró que si se apunta formalmente Miguel Ángel Martínez Espinosa, dirigente estatal del blanquiazul con licencia, éste sería juez y parte.",
    "Media": "http://www.ntrguadalajara.com/evidimg/2018-02-03_09-02-47___3916.png",
    "Media Credit": "El Diario NTR",
    "Media Caption": "<a href=\"http://www.ntrguadalajara.com/post.php?id_nota=91890\">Leer nota</a>",
    "Media Thumbnail": "https://seeklogo.com/images/P/PAN-logo-5C037F689C-seeklogo.com.png",
    "Type": "",
    "Group": "Estatal",
    "Background": "",
    "Candidato": "PAN",
    "Tema": "",
    "Fuente": ""
  }
];